pygments:  true
permalink: /blog/:year/:month/:day/:title.html
markdown:  redcarpet
exclude:   [ README.md, Gemfile ]
profile:
    name: "Maxime Horcholle"
    status: "Développeur PHP"
    aged: "24 ans"
    email: "maxime.horcholle@gmail.com"
    studies:
        - 2015: "Master Architecture logicielle (ESGI - Paris)"
        - 2012: "Licence professionnelle Conception des systèmes d'information, intégration et décision (Paris 8 - Montreuil)"
        - 2011: "BTS Informatique de Gestion (Lycée Voillaume - Aulnay sous Bois)"
    skills:
        language:
            - "PHP"
            - "Javascript"
            - "Android"
            - "XML"
            - "JSON"
            - "YAML"
            - "HTML"
            - "Twig"
            - "CSS"
        framework:
            - "Symfony2"
            - "PHPUnit"
        tool:
            - "Git"
            - "Vagrant"
            - "Redis"
            - "Docker"
            - "Linux"
    hobbies:
        - "OpenSource"
        - "Code quality"
        - "Music"
    links:
        - github: https://github.com/mhor
        - email: maxime.horcholle@gmail.com
        - linkdIn: https://www.linkedin.com/pub/maxime-horcholle/72/912/675
